### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/eleventy-plugin-directus#1]
Here is what I am working on:

- [ ] better way to fetch related data: fetch all collections without the related data and provide filter to get related data (Here is [a discussion about why and how difficult it is](https://github.com/directus/directus/discussions/17293))
- [ ] provide a filter to get related data: `{% assign page = item | directus_relation: 'link' %}`
- [ ] provide a filter to get translation: `{% assign translated = item | directus_translate: 'fr' %}`
- [ ] provide a filter to get assets URL and optionally download it from directus to eleventy's asset folder: `<img src="{{ item.image | directus_asseturl: true }}">` #3 
- [ ] use eleventy fetch plugin to fetch directus data
- [ ] doc to use with [11ty image plugin](https://www.11ty.dev/docs/plugins/image/) #3 

cc @eitchtee
